// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth() {
  return window['go']['app']['App']['CheckAuth']();
}

export function DeleteOlderThan(arg1, arg2) {
  return window['go']['app']['App']['DeleteOlderThan'](arg1, arg2);
}

export function DistinctLevels(arg1) {
  return window['go']['app']['App']['DistinctLevels'](arg1);
}

export function GetRawLine(arg1, arg2) {
  return window['go']['app']['App']['GetRawLine'](arg1, arg2);
}

export function ListBuckets() {
  return window['go']['app']['App']['ListBuckets']();
}

export function ListLoadedBuckets() {
  return window['go']['app']['App']['ListLoadedBuckets']();
}

export function ListObjects(arg1, arg2) {
  return window['go']['app']['App']['ListObjects'](arg1, arg2);
}

export function LoadFiles(arg1, arg2) {
  return window['go']['app']['App']['LoadFiles'](arg1, arg2);
}

export function Search(arg1, arg2) {
  return window['go']['app']['App']['Search'](arg1, arg2);
}
