// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gcp} from '../models';
import {store} from '../models';
import {parse} from '../models';
import {gcs} from '../models';
import {app} from '../models';

export function CheckAuth():Promise<gcp.AuthStatus>;

export function CreateWiretap(arg1:store.WiretapInput):Promise<store.Wiretap>;

export function DefaultFields():Promise<Array<parse.Field>>;

export function DeleteWiretap(arg1:string):Promise<void>;

export function DistinctLevels(arg1:string):Promise<Array<string>>;

export function GetRawLine(arg1:string,arg2:string):Promise<string>;

export function ListBuckets(arg1:string):Promise<Array<gcs.BucketInfo>>;

export function ListObjectsForWiretap(arg1:string,arg2:string):Promise<Array<app.FileEntry>>;

export function ListProjects():Promise<Array<gcp.Project>>;

export function ListWiretaps():Promise<Array<store.Wiretap>>;

export function LoadFilesNow(arg1:string,arg2:Array<string>):Promise<Array<app.LoadSummary>>;

export function RunRetentionNow(arg1:string):Promise<number>;

export function Search(arg1:string,arg2:store.Filters):Promise<store.SearchResult>;

export function SyncWiretapNow(arg1:string):Promise<number>;

export function UpdateWiretap(arg1:string,arg2:store.WiretapInput):Promise<store.Wiretap>;
