// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gcp} from '../models';
import {time} from '../models';
import {gcs} from '../models';
import {app} from '../models';
import {store} from '../models';

export function CheckAuth():Promise<gcp.AuthStatus>;

export function DeleteOlderThan(arg1:string,arg2:time.Time):Promise<number>;

export function DistinctLevels(arg1:string):Promise<Array<string>>;

export function GetRawLine(arg1:string,arg2:string):Promise<string>;

export function ListBuckets():Promise<Array<gcs.BucketInfo>>;

export function ListLoadedBuckets():Promise<Array<string>>;

export function ListObjects(arg1:string,arg2:string):Promise<Array<app.FileEntry>>;

export function LoadFiles(arg1:string,arg2:Array<string>):Promise<Array<app.LoadSummary>>;

export function Search(arg1:string,arg2:store.Filters):Promise<store.SearchResult>;
